config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :books do
    resources :sections
  end

  resources :reviews
  
  root to: 'static_pages#show', id: "home"

  resources :static_pages, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id                       :bigint           not null, primary key
#  category                 :string
#  description              :text
#  expected_completion_date :datetime
#  genre                    :string
#  title                    :string           not null
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  user_id                  :bigint
#
# Indexes
#
#  index_books_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Book < ApplicationRecord
  belongs_to :user
  paginates_per 10
  has_many :sections, dependent: :destroy
  validates :title, presence: true
end

app/models/review.rb
# == Schema Information
#
# Table name: reviews
#
#  id         :bigint           not null, primary key
#  state      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  book_id    :bigint
#
# Indexes
#
#  index_reviews_on_book_id  (book_id)
#  index_reviews_on_state    (state)
#
# Foreign Keys
#
#  fk_rails_...  (book_id => books.id)
#
class Review < ApplicationRecord
  include AASM

  enum state: {
    pending: "pending",
    assigned: "assigned",
    approved: "approved",
    rejected: "rejected"
  }

  aasm column: :state, enum: true do
    state :pending, initial: true
    state :assigned, :approved, :rejected

    event :reviewing do
      transitions from: :pending, to: :assigned
    end

    event :approve do
      transitions from: :assigned, to: :approved
    end

    event :reject do
      transitions from: :assigned, to: :rejected
    end
  end

  belongs_to :book

end

app/models/section.rb
# == Schema Information
#
# Table name: sections
#
#  id         :bigint           not null, primary key
#  content    :text             default("")
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  book_id    :bigint           not null
#
# Indexes
#
#  index_sections_on_book_id  (book_id)
#
# Foreign Keys
#
#  fk_rails_...  (book_id => books.id)
#
class Section < ApplicationRecord
  belongs_to :book
  validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  confirmation_sent_at   :datetime
#  confirmation_token     :string
#  confirmed_at           :datetime
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    books_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: %i(edit update show destroy)

  def new
    @book = Book.new
  end

  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def index
    if params.key?(:q)
      @books = current_user.books.ransack(query_params).result
    else
      @books = current_user.books.all
    end

    @books = @books.page(params[:page])
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @book.destroy
    redirect_to action: :index
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :expected_completion_date, :category, :genre)
  end

  def set_book
    @book = current_user.books.find(params[:id])
  end

  def query_params
    params.require(:q).permit(:title_eq, :title_cont, :title_start)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

  before_action :set_book
  before_action :set_section, only: %i(show edit update destroy)

  def index
    @sections = @book.sections
  end

  def new
    @section = @book.sections.new
  end

  def create
    @section = @book.sections.new(section_params)

    if @section.save
      redirect_to action: :index
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @section.update(section_params)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    @section.destroy
    redirect_to action: :index
  end

  private
  def section_params
    params.require(:section).permit(:name, :content)
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  def set_section
    @section = @book.sections.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  AVAILABLE_PAGES = %w[home about]

  def show
    @page_name = AVAILABLE_PAGES.include?(params[:id]) ? params[:id] : "not_found"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_name(controller_name, action_name)
    if controller_name != "static_pages"
      " | #{controller_name.titleize}"
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/books/_form.html.slim
= simple_form_for(book) do |form|
  .form-field
    = form.input :title, label: "Title"
  .form-field
    = form.input :description, label: "Description"
  .form-field
    = form.input :expected_completion_date, as: :date, label: "Expected Completion Date"
  .form-field
    = form.input :category, label: "Category"
  .form-field
    = form.input :genre, label: "Genre"
  .actions.d-flex.flex-row
    = form.button :submit, class: "btn-primary"
    = link_to  "Back", books_path, class: "btn btn-outline-primary ml-2"

app/views/books/edit.html.slim
h1
  | Edit Book
= render partial: "books/form", locals: { book: @book }

app/views/books/index.html.slim
h1
  | List books

.search_form.py-2
  = simple_form_for(:q, url: books_path, method: :get) do |form|
    .form-field
      = form.input :title_cont, label: "Search", input_html: { value: params.dig(:q, :title_cont) }
    .actions
      = form.button :submit, "Search", class: 'btn-primary'

table.table
  thread
    tr
      th scope="col" ID
      th scope="col" Title
      th scope="col" Completion Date
      th scope="col" Category
      th scope="col" Genre
      th scope="col" Handle

  - @books.each do |book|
    tr
      td
        = book.id
      td
        = book.title
      td
        = book.expected_completion_date
      td
        = book.category
      td
        = book.genre
      td.d-flex.flex-row.justify-content-around
        = link_to "Edit", edit_book_path(book)
        = link_to "Show", book_path(book)
        = link_to "Sections", book_sections_path(book)
        = link_to  "Delete", book_path(book), method: :delete, data: {confirm: "Are you sure?"}
div
  = paginate @books, window: 2
div
  = link_to  "Add new book", new_book_path, class: "btn btn-outline-primary"

app/views/books/new.html.slim
h1
  | New Book
= render partial: "books/form", locals: { book: @book }

app/views/books/show.html.slim
h1
  = @book.title
div.py-2
  .h5
    |  Description:
  = simple_format @book.description
div.py-2
  .h5
    |  Completion Date:
  = @book.expected_completion_date
div.py-2
  .h5
    |  Category:
  = @book.category
div.py-2
  .h5
    |  Genre:
  = @book.genre
div
  = link_to  "Edit", edit_book_path(@book), class: "btn btn-primary mr-2"
  = link_to  "Back", books_path, class: "btn btn-outline-primary"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Pooh's home
      = page_name(controller_name, action_name)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header= render partial: "shared/header"
    section.main.py-5
      .container= yield
    footer= render partial: "shared/footer"

app/views/reviews/_form.html.slim
= simple_form_for(review) do |form|
  .form-field
    = form.association :book, collection: current_user.books, prompt: "Choose the book", label: false
  .actions.d-flex.flex-row
    = form.button :submit, class: "btn-primary"
    = link_to  "Back", books_path, class: "btn btn-outline-primary ml-2"

app/views/reviews/new.html.slim
H1
  | Review book
=render partial: "reviews/form", locals: { review: @review}

app/views/sections/_form.html.slim
= simple_form_for([@book, @section]) do |form|
  .form-field
    = form.input :name, label: "Name"
  .form-field
    = form.input :content, label: "Content"
  .actions
    = form.button :submit, class: "btn btn-primary mr-2"
    = link_to "Back", book_sections_path, class: "btn btn-outline-primary"

app/views/sections/edit.html.slim
h1
  |  Edit Section
= render partial: "sections/form", locals: {section: @section}

app/views/sections/index.html.slim
h1
  = @book.title
table.table
  - @sections.each do |s|
    tr
      td
        = s.name
      td.d-flex.flex-row.justify-content-end
        = link_to "Show", book_section_path(s.book, s), class: "px-2"
        = link_to "Edit", edit_book_section_path(s.book, s), class: "px-2"
        = link_to "Delete", book_section_path(s.book, s), method: :delete, data: {confirm: "Are you sure?"}
div
  = link_to "Add Section", new_book_section_path, class: "btn btn-primary mr-2"
  = link_to "Back", books_path, class: "btn btn-outline-primary"

app/views/sections/new.html.slim
h1
  |  Create sections
= render partial: "sections/form", locals: { section: @section}

app/views/sections/show.html.slim
h1
  |  Show Section 
div
  |  Name: 
  = @section.name
div
  |  Content: 
  = simple_format @section.content
div
  = link_to  "Back", book_sections_path(@section.book)

app/views/shared/_footer.html.slim
.container-fluid.bg-dark.text-white.pb-5
  .row.pb-5
    .col-12
      .container
        .row.py-5
          .col-12.text-center
            i.display-3.fas.fa-book-reader
        .row
          .col-12
            .d-flex.flex-column.flex-md-row.justify-content-between
              div.py-sm-2.py-md-0
                div
                  h4 About
                div
                  a.text-reset href='#' About Pooh's Publisher
                div
                  a.text-reset href='#' Blog
                div
                  a.text-reset href='#' Contact
                div
                  a.text-reset href='#' Press

              div.py-sm-2.py-md-0
                div
                  h4 Authors
                div
                  a.text-reset href='#' Why Pooh's Publisher
                div
                  a.text-reset href='#' Testimonials
                div
                  a.text-reset href='#' Climate Change
                div
                  a.text-reset href='#' Simplifying
                div
                  a.text-reset href='#' Grandfathering
                div
                  a.text-reset href='#' Freemium
                div
                  a.text-reset href='#' Manifesto
                div
                  a.text-reset href='#' COVID-19

              div.py-sm-2.py-md-0
                div
                  h4 Authors Support
                div
                  a.text-reset href='#' The Pooh's Manual
                div
                  a.text-reset href='#' Author Help Center
                div
                  a.text-reset href='#' Pooh's Authors Forum
                div
                  a.text-reset href='#' The Markua Manual
                div
                  a.text-reset href='#' The Pooh's Flavoured
                div
                  a.text-reset href='#' Markdown Manual
                div
                  a.text-reset href='#' Supported Languages
                div
                  a.text-reset href='#' API Docs

              div.py-sm-2.py-md-0
                div
                  h4 More
                div
                  a.text-reset href='#' Reader Help Center
                div
                  a.text-reset href='#' Newsletters
                div
                  a.text-reset href='#' Podcast
                div
                  a.text-reset href='#' Redeem a Token
                div
                  a.text-reset href='#' Causes

              div.py-sm-2.py-md-0
                div
                  h4 Legal
                div
                  a.text-reset href='#' Terms of Service
                div
                  a.text-reset href='#' Copyright Policy
                div
                  a.text-reset href='#' Privacy Policy

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.text-white
  a.navbar-brand href="#" Pooh's Publisher
  button.navbar-toggler type="button" data-toggle="collapse" data-target="#menu"

  div.collapse.navbar-collapse id="menu"
    ul.navbar-nav
      li.nav-item.active
        = link_to "Home", root_path, class: "nav-link"
      li.nav-item
        a.nav-link href="#" About
      li.nav-item.dropdown
        a.nav-link.dropdown-toggle#service href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" Service
        .dropdown-menu aria-labelledby="service"
          .dropdown-item
            = link_to "Write Book", books_path
          .dropdown-item
            = link_to "Review Book", new_review_path
          .dropdown-item href="#" Buy Book

  form.form-inline.py-2.d-flex.pr-1
    .form-wrap
      .input-group.mr-1
        .input-group-prepend
          .input-group-text.bg-white
            i.fas.fa-search
        input.form-control.border-left-0 type="search" placeholder="Search title or author" aria-label="Search"
    - if user_signed_in?
      .dropdown
        = link_to current_user.email, "#", id: "account-dropdown", data: {toggle: "dropdown" }, class: "text-white pl-2"
        .dropdown-menu aria_labelledby="account-dropdown"
          = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item"
    - else
      = link_to "Sign In", new_user_session_path, class: "btn btn-outline-light m-1"
      = link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-light m-1"

app/views/static_pages/_about.html.slim
h1 Aboutpage

app/views/static_pages/_home.html.slim
.container
  .row.py-5
    .col-12.col-md-6.col-lg-4.py-4.py-md-0
      .row.py-4
        .col-sm-6.col-md-4
          = image_pack_tag 'icon.jpg', width: '100%'
        .col-sm-6.col-md-8
          h4 PUBLISH EARLY, PUBLISH OFTEN
      .intro
        h4 Earn 80% royalties publishing on Leanpub
        p
          | Authors have earned over&#32;
          strong $8,000,000&#32;
          | publishing ebooks and courses on Leanpub. You can use Leanpub to&#32;
          strong  write, publish and sell&#32;
          | an ebook or online course as well.

        p
          | You can write your book in our&#32;
          strong visual editor&#32;
          | or in a plain text document formatted in&#32;
          strong Markdown&#32;
          | . Either way, you can publish it as a Leanpub ebook with&#32;
          strong one click&#32;
          | . You can publish your book while you're writing it, or wait until it is done: it's up to you.

        p
          | Or, if you've already written a book, you can&#32;
          strong upload a completed ebook&#32;
          | to sell in our store.

        p
          | You can&#32;
          strong create a Leanpub course in Markdown&#32;
          | as well. Leanpub courses are like Leanpub books, but learners read them and do the quizzes and exercises on the Leanpub website.

      .d-flex.flex-column.flex-md-row.btn-group role="group"
        div.text-center
          button.btn.btn-primary.m-1 href="#" Create a Book or Course
        div.text-center
          button.btn.btn-light.m-1 href="#" Learn more

    .col-12.col-md-6.col-lg-4.py-4.py-md-0
      = image_pack_tag 'cover.jpg', width: '100%'

    .col-12.col-lg-4.py-4.py-md-0
      span.border-bottom.border-primary.pb-2 FEATU
      | RED BOOK
      h4.mt-5.mb-2 The naked truth about working from home
      span
        = image_pack_tag 'author.jpg', width: '30', height: '30', class: 'rounded-circle'
      span.px-2
        u Scott Anderson
      .intro.h5.pt-3
        p.font-weight-bold.py-1 Should you "dress for success" when working from home?
        p.py-1 Nope. What a waste!
        p.font-weight-bold.py-1 Can you work from home and have a healthy work-life balance?
        p.py-1 Yes, in fact, your opportunity for a balanced life improves.
        p.py-1 Don’t risk the wrong kind of viral internet fame. Avoid the pitfalls and learn how to optimize your WFH environment to boost your productivity.

      .d-flex.flex-row
        .price.m-2
          .h4.text-center $5.99
          p.text-muted MINIMUM PRICE
        .price.m-2
          .h4.text-center $9.99
          p
            span.text-muted SUGGESTED PRICE
            i.ml-2.fas.fa-question-circle

      .btn-group role='group'
        button.btn.btn-primary.m-1 href='#' Add Ebook to Cart
        button.btn.btn-light.m-1 href='#' Learn more

app/views/static_pages/_not_found.html.slim
h1 NOT FOUND

app/views/static_pages/show.html.slim
= render partial: "static_pages/#{@page_name}"